#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo $1
echo Versioning...
npm version prerelease --preid=beta
react-native-version --never-amend
git add -A .
git commit -m "Version upgraded"
git push origin HEAD --no-verify
