name: Bump version
on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump version and push tag
        uses: TriPSs/conventional-changelog-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-message: "chore(release): {version}"
          preset: "angular"
          tag-prefix: ""
          output-file: "CHANGELOG.md"
